name: client
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  freezed: ^2.4.6
  http: ^1.1.0

dev_dependencies:
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  build_test: ^2.2.0
